### ISSUE TITLE
como se usa isso no Arch?

### ISSUE THREAD

**Issue by DaniV5** [luizoti/docker-smb#1]
sabe me dizer como posso configurar isso manualmente?

**Comment by luizoti** [comment]
Os comandos do Docker teoricamente são os mesmos, mas todo o resto tem que ser adaptado nos arquivos de instalação e configuração.

Inicialmente modifique o ´install-samba.sh´ para instalar corretamente o docker e dependências no Arch, e modifique demais comandos pra se adequarem ao sistema.
